name: front-CI/CD

on:
  push:
    branches: [main]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
          instance-ids: ${{secrets.INSTANCE_ID}}

          working-directory: /home/ubuntu/mkchat
          command: ls -al
